version: '3'

services:
  hello_service:
    build:
      context: ./hello
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: always

  goodbye_service:
    build:
      context: ./goodbye
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 