version: '3'

services:
  hello_service:
    build:
      context: ./hello
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./hello:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--root-path", "/"]
    networks:
      - app_network

  goodbye_service:
    build:
      context: ./goodbye
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./goodbye:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--root-path", "/"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 